### PR TITLE
Add workflow for creating dev release

### PR DESCRIPTION
**Pull request by OptimumOpium**

### CODE REVIEW

**Review by vdonadze — COMMENTED** [review]
don't we need to include scan-job for trivy dependency check ? or is it already part of compound-java.yml ?

**Comment by OptimumOpium** [comment]
> please add the `dev-version-*` pattern to ignore list in the .github/workflows/dev-java-publish-sonatype.yml

I don't agree with that. I don't want to have a dev release for each push to dev branch. I even think that we should remove the this part from dev workflow at all
```
  push:
    branches:
      - dev-version-*
    paths:
      - gradle.properties
 ```
And trigger the dev release manually when we are sure that we need it

**Comment by OptimumOpium** [comment]
> don't we need to include scan-job for trivy dependency check ? or is it already part of compound-java.yml ?

Yes, it is
https://github.com/th2-net/.github/blob/main/.github/workflows/compound-java.yml#L121

**Comment by OptimumOpium** [comment]
@Nikita-Smirnov-Exactpro Are you okay to leave the dev-snapshot along with the dev-release? We still want to have snapshots for dev branch to test it and implement integration with dev version. Once we sure that the dev branch is stable we can create a dev-release (manually or on version change and push)

**Review by Nikita-Smirnov-Exactpro — APPROVED** [review]

**Pull request merged**
